name: Publish Docker Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Username must be lowercase
      - name: Sanitize repo slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'.toLowerCase()

      - name: Normal image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.repo_slug.outputs.result }}:latest
      
      - name: Full image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            FULL_BUILD=true
          tags: ${{ steps.repo_slug.outputs.result }}:full
      
