name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]


jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Checkout
        uses: actions/checkout@v6

      - name: Choose files to deploy
        run: |
          mkdir public
          mv wsl.ps1 public
          mv user.sh public
          mv apt.sh public
          mv pacman.sh public
          mv install_ghidra.sh public
          mv ghidra_settings.py public
          mv aptvm.sh public

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    needs: upload
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
